/**
 * Parcel module id: 92GyB
 * Resolved path: @plasmohq/messaging.js
 * Dependencies:
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 *   nanoid -> g2QpR  =>  nanoid.js
 *
 * npm-backed (@plasmohq/messaging). Generated by scripts/replace-remaining-vendors-with-npm.mjs — do not hand-edit.
 */

var helpers = e("@parcel/transformer-js/src/esmodule-helpers.js")
helpers.defineInteropFlag(r)

var __jrReq = e

var __mod = (function () {
  var __cjsModule = { exports: {} }
  var module = __cjsModule
  var exports = __cjsModule.exports
;var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// scripts/_remaining-vendor-tmp/entry-92GyB.mjs
var entry_92GyB_exports = {};
__export(entry_92GyB_exports, {
  default: () => entry_92GyB_default,
  relay: () => E,
  relayMessage: () => M,
  sendToActiveContentScript: () => h,
  sendToBackground: () => p,
  sendToBackgroundViaRelay: () => u,
  sendToContentScript: () => x,
  sendViaRelay: () => S
});
module.exports = __toCommonJS(entry_92GyB_exports);

// node_modules/@plasmohq/messaging/dist/index.js
var dist_exports = {};
__export(dist_exports, {
  relay: () => E,
  relayMessage: () => M,
  sendToActiveContentScript: () => h,
  sendToBackground: () => p,
  sendToBackgroundViaRelay: () => u,
  sendToContentScript: () => x,
  sendViaRelay: () => S
});
var import_nanoid = __jrReq("nanoid");
var l = globalThis.browser?.tabs || globalThis.chrome?.tabs;
var d = () => {
  let e = globalThis.browser?.runtime || globalThis.chrome?.runtime;
  if (!e) throw new Error("Extension runtime is not available");
  return e;
};
var i = () => {
  if (!l) throw new Error("Extension tabs API is not available");
  return l;
};
var m = async () => {
  let e = i(), [a] = await e.query({ active: true, currentWindow: true });
  return a;
};
var g = (e, a) => !a.__internal && e.source === globalThis.window && e.data.name === a.name && (a.relayId === void 0 || e.data.relayId === a.relayId);
var c = (e, a, n = globalThis.window) => {
  let r = async (s) => {
    if (g(s, e) && !s.data.relayed) {
      let o = { name: e.name, relayId: e.relayId, body: s.data.body }, t = await a?.(o);
      n.postMessage({ name: e.name, relayId: e.relayId, instanceId: s.data.instanceId, body: t, relayed: true }, { targetOrigin: e.targetOrigin || "/" });
    }
  };
  return n.addEventListener("message", r), () => n.removeEventListener("message", r);
};
var y = (e, a = globalThis.window) => new Promise((n, r) => {
  let s = (0, import_nanoid.nanoid)(), o = new AbortController();
  a.addEventListener("message", (t) => {
    g(t, e) && t.data.relayed && t.data.instanceId === s && (n(t.data.body), o.abort());
  }, { signal: o.signal }), a.postMessage({ ...e, instanceId: s }, { targetOrigin: e.targetOrigin || "/" });
});
var p = async (e) => d().sendMessage(e.extensionId ?? null, e);
var x = async (e) => {
  let a = typeof e.tabId == "number" ? e.tabId : (await m())?.id;
  if (!a) throw new Error("No active tab found to send message to.");
  return i().sendMessage(a, e);
};
var h = x;
var M = (e) => c(e, p);
var E = M;
var u = y;
var S = u;

// scripts/_remaining-vendor-tmp/entry-92GyB.mjs
var entry_92GyB_default = void 0 !== void 0 ? void 0 : dist_exports;

  var out = module.exports
  if (out && typeof out === "object" && out.__esModule && "default" in out) {
    var names = Object.keys(out).filter(function (k) {
      return k !== "default" && k !== "__esModule"
    })
    if (names.length) return out
    return out.default
  }
  return out
})()

if (typeof __mod === "function") {
  helpers.export(r, "default", function () { return __mod })
  r.default = __mod
} else if (__mod && typeof __mod === "object") {
  for (var __k in __mod) {
    if (Object.prototype.hasOwnProperty.call(__mod, __k) && __k !== "__esModule") {
      ;(function (key) {
        helpers.export(r, key, function () { return __mod[key] })
        r[key] = __mod[key]
      })(__k)
    }
  }
  r.default = __mod.default !== undefined ? __mod.default : __mod
  if (__mod.default !== undefined) {
    helpers.export(r, "default", function () { return __mod.default })
  }
} else {
  r.default = __mod
  helpers.export(r, "default", function () { return __mod })
}
