/**
 * Parcel module id: 7kZkl
 * Resolved path: src/contents/sites/hubspot/rules.js
 * Dependencies:
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 *   ~core/enums -> 1O3nc  =>  src/core/enums.js
 */

var n=e("@parcel/transformer-js/src/esmodule-helpers.js");n.defineInteropFlag(r),n.export(r,"getHubspotLabelText",()=>u),n.export(r,"isHubspotFieldRequired",()=>c),n.export(r,"extractRules",()=>y),n.export(r,"getFormSnapshot",()=>v);var o=e("~core/enums");let i=".hs-form-field",a=e=>e?.replace(/\s+/g," ").replace(/\s+\*/g,"*").trim()||"",l=e=>a(e).replace(/\s*\*$/,"").trim(),s=e=>e.querySelector("label, legend, span"),u=e=>{let t=e.querySelector("input[label], textarea[label], select[label]"),r=t?.getAttribute("label");if(r)return l(r);let n=s(e);return l(n?.textContent||"")},c=e=>!!e.querySelector(".hs-form-required")||!!e.querySelector("[required]")||/\*$/.test(a(s(e)?.textContent||"")),d=e=>Array.from(e.options).map(e=>a(e.textContent)).filter(e=>e&&!/^[-\s]*select[-\s]*$/i.test(e)),f=e=>{let t=e.closest("label");return a(t?.textContent||e.value)},p=(e,t,r)=>{let n=e.querySelector('textarea, input:not([type="hidden"]):not([type="file"]):not([type="radio"]):not([type="checkbox"]):not([type="button"]):not([type="submit"])');return n?{type:o.FIELD_TYPE.TEXT,label:t,required:r,$input:n,$label:s(e)||e}:null},m=(e,t,r)=>{let n=e.querySelector('input#gh-apply-location[name="location"], input.autocomplete.pac-target-input');return n?{type:o.FIELD_TYPE.SEARCH,label:t,required:r,$input:n,$label:s(e)||e,description:"City, State/Province, Country"}:null},h=(e,t,r)=>{let n=e.querySelector("select");return n?{type:o.FIELD_TYPE.SELECT,label:t,required:r,options:d(n),$input:n,$label:s(e)||e}:null},g=(e,t,r)=>{let n=Array.from(e.querySelectorAll('input[type="checkbox"]'));return n.length?{type:o.FIELD_TYPE.CHECKBOX,label:t,required:r,options:n.map(f).filter(Boolean),$checkboxs:n,$input:n[0],$label:s(e)||e}:null},b=(e,t,r)=>{let n=Array.from(e.querySelectorAll('input[type="radio"]'));return n.length?{type:o.FIELD_TYPE.RADIO,label:t,required:r,options:n.map(f).filter(Boolean),$input:n,$radioParent:e,$label:s(e)||e}:null};function y(e=document){let t=Array.from(e.querySelectorAll(i)),r=[];for(let e of t){if(e.querySelector('input[type="file"]'))continue;let t=u(e);if(!t)continue;let n=c(e),o=g(e,t,n)||b(e,t,n)||h(e,t,n)||m(e,t,n)||p(e,t,n);o&&r.push(o)}return r}function v(e=document){let t={},r=Array.from(e.querySelectorAll(i));for(let e of r){let r=u(e);if(!r)continue;let n=e.querySelector('input[type="file"]');if(n){let n=a(e.textContent);t[r]=n;continue}let o=e.querySelector("select");if(o){let e=o.selectedOptions?.[0];t[r]=a(e?.textContent||o.value);continue}let i=Array.from(e.querySelectorAll('input[type="checkbox"]:checked, input[type="radio"]:checked'));if(i.length){t[r]=i.map(f).filter(Boolean);continue}let l=e.querySelector('textarea, input:not([type="hidden"]):not([type="file"]):not([type="radio"]):not([type="checkbox"]):not([type="button"]):not([type="submit"])');l&&(t[r]=l.value||"")}return t}
