/**
 * Parcel module id: e2WM4
 * Resolved path: src/enums/storage.js
 * Dependencies:
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 */

var n,o=e("@parcel/transformer-js/src/esmodule-helpers.js");o.defineInteropFlag(r),o.export(r,"STORAGE_KEY",()=>n),function(e){e.GLOBAL_CONFIG_TURN_PAGE="GLOBAL_CONFIG_TURN_PAGE",e.GLOBAL_CONFIG_DEFAULT_VIEW="GLOBAL_CONFIG_DEFAULT_VIEW",e.RESUME_COLLECTION="RESUME_COLLECTION",e.RESUME_TEMPLATE="RESUME_TEMPLATE",e.LAST_USED_RESUME="LAST_USED_RESUME",e.LAST_USED_ORIGINAL_RESUME="LAST_USED_ORIGINAL_RESUME",e.FIRST_LOAD_RESUME="FIRST_LOAD_RESUME",e.DISABLE_RESUME_UPLOAD="DISABLE_RESUME_UPLOAD",e.DONT_ASK_AGAIN_AUTOFILL="DONT_ASK_AGAIN_AUTOFILL",e.EVAL_DISABLE_RESUME_AUTOFILL_SYNC="EVAL_DISABLE_RESUME_AUTOFILL_SYNC",e.TURBO_ENTRY_CLOSED="TURBO_ENTRY_CLOSED",e.AUTOFILL_INFO_SNAPSHOT="AUTOFILL_INFO_SNAPSHOT",e.STAR_RATING_SITE_FILLS="STAR_RATING_SITE_FILLS",e.STAR_RATING_LAST_EXPOSURE_TIME="STAR_RATING_LAST_EXPOSURE_TIME",e.STAR_RATING_EXPOSURE_COUNT_NO_CLICK="STAR_RATING_EXPOSURE_COUNT_NO_CLICK",e.STAR_RATING_CLICKED="STAR_RATING_CLICKED",e.HIDDEN_DOMAINS="HIDDEN_DOMAINS",e.HIDDEN_ALL_WEBSITES="HIDDEN_ALL_WEBSITES"}(n||(n={}))
