// @ts-nocheck
/**
 * Chrome storage key names used across helper-runtime stores and utils.
 */

export enum STORAGE_KEY {
  GLOBAL_CONFIG_TURN_PAGE = "GLOBAL_CONFIG_TURN_PAGE",
  GLOBAL_CONFIG_DEFAULT_VIEW = "GLOBAL_CONFIG_DEFAULT_VIEW",
  RESUME_COLLECTION = "RESUME_COLLECTION",
  RESUME_TEMPLATE = "RESUME_TEMPLATE",
  LAST_USED_RESUME = "LAST_USED_RESUME",
  LAST_USED_ORIGINAL_RESUME = "LAST_USED_ORIGINAL_RESUME",
  FIRST_LOAD_RESUME = "FIRST_LOAD_RESUME",
  DISABLE_RESUME_UPLOAD = "DISABLE_RESUME_UPLOAD",
  DONT_ASK_AGAIN_AUTOFILL = "DONT_ASK_AGAIN_AUTOFILL",
  EVAL_DISABLE_RESUME_AUTOFILL_SYNC = "EVAL_DISABLE_RESUME_AUTOFILL_SYNC",
  TURBO_ENTRY_CLOSED = "TURBO_ENTRY_CLOSED",
  AUTOFILL_INFO_SNAPSHOT = "AUTOFILL_INFO_SNAPSHOT",
  STAR_RATING_SITE_FILLS = "STAR_RATING_SITE_FILLS",
  STAR_RATING_LAST_EXPOSURE_TIME = "STAR_RATING_LAST_EXPOSURE_TIME",
  STAR_RATING_EXPOSURE_COUNT_NO_CLICK = "STAR_RATING_EXPOSURE_COUNT_NO_CLICK",
  STAR_RATING_CLICKED = "STAR_RATING_CLICKED",
  HIDDEN_DOMAINS = "HIDDEN_DOMAINS",
  HIDDEN_ALL_WEBSITES = "HIDDEN_ALL_WEBSITES",
}
