/**
 * Parcel module id: deKYK
 * Resolved path: src/contents/sites/dayforce/agreements.js
 * Dependencies:
 *   ./auth -> 1TnOy  =>  src/contents/sites/dayforce/auth.js
 *   ./policy-link -> 5f7QQ  =>  src/contents/sites/dayforce/policy-link.js
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 *   @plasmohq/messaging -> 92GyB  =>  @plasmohq/messaging.js
 */

var n=e("@parcel/transformer-js/src/esmodule-helpers.js");n.defineInteropFlag(r),n.export(r,"acceptDayforceRegistrationAgreements",()=>c);var o=e("@plasmohq/messaging"),i=e("./auth"),a=e("./policy-link");let l="I agree to Dayforce's Global Privacy Statement and to the Terms of Use, I clicked the links above and reviewed these documents.",s=new WeakSet;function u(e){return!e.closest('[hidden], [aria-hidden="true"]')&&e.getClientRects().length>0&&"hidden"!==window.getComputedStyle(e).visibility}async function c({root:e=document,url:t,isVisible:r=u,openPolicyLink:n=e=>(0,a.openDayforcePolicyLink)(e,e=>(0,o.sendToBackground)({name:"openDayforcePolicyTab",body:{url:e}})),settle:c=()=>new Promise(e=>setTimeout(e,100))}={}){if("register"!==(0,i.getDayforceAuthPageMode)(t))return!1;let d=()=>{let t=Array.from(e.querySelectorAll("main"));if(1!==t.length||!r(t[0]))return null;let n=e=>{let n=Array.from(t[0].querySelectorAll(e));return 1===n.length&&r(n[0])?n[0]:null},o=n('a[href="https://www.dayforce.com/privacy"][target="_blank"]'),i=n('a[href="https://www.dayforce.com/terms"][target="_blank"]'),a=`input[type="checkbox"][role="checkbox"][aria-label="${l}"]`,s=Array.from(t[0].querySelectorAll(`evr-checkbox[arialabelcheckbox="${l}"]`));if(s.length>1||1===s.length&&!r(s[0]))return null;let u=[...Array.from(t[0].querySelectorAll(a)),...Array.from(s[0]?.shadowRoot?.querySelectorAll(a)??[])],c=1===u.length&&r(u[0])?u[0]:null;return o&&i&&c&&!c.disabled&&"true"!==c.getAttribute("aria-disabled")?{privacy:o,terms:i,checkbox:c}:null};try{let e=d();if(!e)return!1;if(s.has(e.checkbox)&&e.checkbox.checked)return!0;if(!await n(e.privacy)||(await c(),!(e=d())||!await n(e.terms))||(await c(),!(e=d())||e.checkbox.checked&&(e.checkbox.click(),await c(),!(e=d())||e.checkbox.checked))||(e.checkbox.click(),await c(),!(e=d())||!e.checkbox.checked||"true"!==e.checkbox.getAttribute("aria-checked")))return!1;return s.add(e.checkbox),!0}catch{return!1}}
