// @ts-nocheck
/**
 * Shared autofill constants (states, sources, z-index, OracleCloud degrees).
 * Source of truth — synced to constants.js for the Parcel helper bundle.
 */

/** US / CA / UK subdivision code -> display name. */
export const STATE_MAP = {
  AL: "Alabama",
  AK: "Alaska",
  AS: "American Samoa",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District of Columbia",
  FL: "Florida",
  GA: "Georgia",
  GU: "Guam",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VI: "Virgin Islands",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
  AB: "Alberta",
  BC: "British Columbia",
  MB: "Manitoba",
  NB: "New Brunswick",
  NL: "Newfoundland and Labrador",
  NS: "Nova Scotia",
  ON: "Ontario",
  PE: "Prince Edward Island",
  QC: "Quebec",
  SK: "Saskatchewan",
  NT: "Northwest Territories",
  NU: "Nunavut",
  YT: "Yukon",
  ENG: "England",
  NIR: "Northern Ireland",
  SCT: "Scotland",
  WLS: "Wales",
}

/** Common “How did you hear about us?” option values. */
export const SOURCE_VALUES = [
  "Jobright",
  "LinkedIn",
  "External",
  "Other",
  "Indeed",
  "Corporate Website",
  "Glassdoor",
  "Job Boards",
  "Job Board",
  "Website",
  "Source",
  "Not Listed",
]

/** Z-index for the in-page helper modal / status UI. */
export const HELPER_MODAL_Z_INDEX = 1200

/** OracleCloud degree label → normalized profile degree. */
export const ORACLECLOUD_DEGREE_VALUES = {
  "Higher Degree": "Doctorate",
  "Master's Degree": "Masters",
  "Doctorate Degree (over 19 years)": "Doctorate",
  "Associate's Degree/College Diploma": "Associates",
  "Bachelor's Degree": "Bachelors",
  "HS Diploma": "High School Diploma",
  "Non-Degree Program": "None",
  None: "None",
  "Technical Diploma": "Vocational / Technical Degree",
  Other: "Other",
}
