/**
 * Parcel module id: 4u8XV
 * Resolved path: src/model.js
 * Dependencies:
 *   ./constants -> 3rdkr  =>  src/forms/constants.js
 *   ./utils/address-lookup -> j5kd9  =>  src/utils/address-lookup.js
 *   ./utils/date-format -> 3nEVv  =>  src/components/Editor/utils/date-format.js
 *   ./utils/location-normalizer -> 2dOam  =>  src/utils/location-normalizer.js
 *   ./utils/phone-country-code -> b8ARY  =>  src/utils/phone-country-code.js
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 *   ~api/autofill-signup-information -> 52vOt  =>  src/api/autofill-signup-information.js
 *   ~utils/skill-list -> 74lkH  =>  src/utils/skill-list.js
 */

var n=e("@parcel/transformer-js/src/esmodule-helpers.js");n.defineInteropFlag(r),n.export(r,"createEducationItem",()=>p),n.export(r,"createWorkItem",()=>m),n.export(r,"resolveCountryCode",()=>h),n.export(r,"buildAutofillInfoData",()=>g);var o=e("~api/autofill-signup-information"),i=e("~utils/skill-list"),a=e("./constants"),l=e("./utils/address-lookup"),s=e("./utils/date-format"),u=e("./utils/location-normalizer"),c=e("./utils/phone-country-code");let d=0,f=()=>`autofill-info-${d++}`,p=e=>({id:f(),schoolName:"",accreditation:"",gap:"",startDate:"",endDate:"",isCurrent:!1,...e}),m=e=>({id:f(),companyName:"",jobTitle:"",city:"",startDate:"",endDate:"",summary:"",descriptions:[],...e}),h=e=>{let t=(0,l.normalizeCountryInput)(e)||e,r=t.toLowerCase().trim();return a.COUNTRY_CODE_MAP[r]??""},g=e=>{let t=e?.personalInfo??{},r=e?.workExperience??[],n=e?.education??[],a=(0,i.extractSkillList)(e),l=e?.employmentInfo??{},d=e?.location??{},f=(0,u.normalizeAutofillLocation)({country:d.country??"",state:d.state??e?.state??"",city:d.city??""});return{personal:{firstName:t.firstName??"",middleName:t.middleName??"",lastName:t.lastName??"",preferredFirstName:t.preferredFirstName??"",preferredMiddleName:t.preferredMiddleName??"",preferredLastName:t.preferredLastName??"",email:t.email??"",phoneType:e?.phoneType??"",phoneCountryCode:(0,c.normalizePhoneCountryCodeWithName)(e?.phoneCountryCode),phone:t.phone_number??"",country:f.country,state:f.state,city:f.city,county:d.county??"",addressLine:e?.addressLine??"",postalCode:d.postCode??"",linkedinUrl:t.linkedin_link||t.linkedin||"",githubUrl:t.github_link||t.github_url||"",websiteUrl:t.personal_site_link||t.personal_site||""},education:n.length>0?n.map(e=>p({schoolName:e.organization??"",accreditation:e.accreditation??"",gap:e.gpa??"",startDate:(0,s.formatAutofillInfoDate)(e.dates?.start_date),endDate:(0,s.formatAutofillInfoDate)(e.dates?.completion_date),isCurrent:!!e.dates?.is_current})):[p()],workExperience:r.length>0?r.map(e=>m({companyName:e.organization??"",jobTitle:e.job_title??"",city:e.location??"",startDate:(0,s.formatAutofillInfoDate)(e.dates?.start_date),endDate:e.dates?.is_current?"Present":(0,s.formatAutofillInfoDate)(e.dates?.completion_date),summary:e.summary??"",descriptions:Array.isArray(e.job_descriptions)?e.job_descriptions:[]})):[m()],skill:Array.isArray(a)&&a.length>0?a:[],equalEmployment:{gender:l.gender??"",ethnicity:l.race??"",veteran:l.veteran??"",disability:l.disability??"",workAuthorization:l.workAuthorization??"",sponsorshipStatus:l.sponsorshipStatus??"",lgbt:l.lgbt??"",hispanic:l.hispanic??"",sexual:Array.isArray(l.sexual)?l.sexual:[]},pronouns:e?.pronouns??"",preference:{salary:e?.salary??"",hiringDate:e?.hiringDate??"",additionalApplicationInfo:e?.additionalApplicationInfo??""},signupInformation:{registrationEmail:(0,o.resolveSignupRegistrationEmail)(e)}}}
