/**
 * Parcel module id: 8BjNp
 * Resolved path: src/components/RoundedRingProgress.js
 * Dependencies:
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 *   react -> 329PG  =>  react-reexport.js
 *   react/jsx-runtime -> 8iOxN  =>  react/jsx-runtime.js
 */

var n=e("@parcel/transformer-js/src/esmodule-helpers.js");n.defineInteropFlag(r);var o=e("react/jsx-runtime"),i=e("react");n.interopDefault(i);let a=({progress:e,width:t=56,height:r=32,strokeWidth:n=2,gradient:a=["#50FABE","#A0FA96"],progressText:l})=>{let s=(0,i.useId)().replace(/:/g,""),u=Math.max(0,Math.min(1,e||0)),c=n/2,d=t-n,f=r-n,p=f/2,m=Math.max(d-f,0),h={left:13,top:9,width:30,height:16},{trackPath:g,trackLength:b}=(0,i.useMemo)(()=>{let e=`M ${t/2} ${r-c} H ${c+p} A ${p} ${p} 0 0 1 ${c+p} ${c} H ${t-c-p} A ${p} ${p} 0 0 1 ${t-c-p} ${r-c} H ${t/2}`;return{trackPath:e,trackLength:2*m+2*Math.PI*p}},[r,c,p,m,t]),y=b*(1-u);return(0,o.jsxs)("div",{style:{position:"relative",width:t,height:r},children:[(0,o.jsxs)("svg",{width:t,height:r,viewBox:`0 0 ${t} ${r}`,style:{display:"block",overflow:"visible"},children:[(0,o.jsx)("defs",{children:(0,o.jsxs)("linearGradient",{id:s,x1:"100%",y1:"0%",x2:"0%",y2:"100%",children:[(0,o.jsx)("stop",{offset:"0%",stopColor:a[0]}),(0,o.jsx)("stop",{offset:"100%",stopColor:a[1]})]})}),(0,o.jsx)("rect",{x:c,y:c,width:d,height:f,rx:p,ry:p,fill:"none",stroke:"#F3F4F5",strokeWidth:n}),(0,o.jsx)("path",{d:g,fill:"none",stroke:`url(#${s})`,strokeWidth:n,strokeDasharray:b,strokeDashoffset:y,strokeLinecap:"round"})]}),void 0!==l&&(0,o.jsx)("div",{style:{position:"absolute",left:h.left,top:h.top,width:h.width,height:h.height,display:"flex",alignItems:"flex-start",justifyContent:"center",pointerEvents:"none"},children:(0,o.jsxs)("div",{style:{display:"inline-flex",alignItems:"flex-start",justifyContent:"center",gap:0,width:"100%",height:"100%",whiteSpace:"nowrap",flexWrap:"nowrap"},children:[(0,o.jsx)("span",{style:{color:"var(--mainFill, var(--base-color-black, #000))",textAlign:"center",fontFamily:"Rubik, Inter, sans-serif",fontSize:"16px",fontWeight:500,fontStyle:"normal",lineHeight:"16px",flexShrink:0},children:l}),(0,o.jsx)("span",{style:{color:"var(--mainFill, var(--base-color-black, #000))",fontFamily:"Rubik, Inter, sans-serif",fontSize:"10px",fontWeight:700,fontStyle:"normal",lineHeight:"15px",flexShrink:0,transform:"translateY(1px)"},children:"%"})]})})]})};r.default=a
