/**
 * Parcel module id: lNYnj
 * Resolved path: src/components/validation.js
 * Dependencies:
 *   ./utils/date-format -> 3nEVv  =>  src/components/Editor/utils/date-format.js
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 *   dayjs -> fnhXp  =>  _tilde_node_modules/dayjs.js
 *   dayjs/plugin/customParseFormat -> g94SE  =>  dayjs/plugin/customParseFormat.js
 */

var n=e("@parcel/transformer-js/src/esmodule-helpers.js");n.defineInteropFlag(r),n.export(r,"collectValidationErrors",()=>f),n.export(r,"getFirstErrorSection",()=>p),n.export(r,"getFirstErrorField",()=>m);var o=e("dayjs"),i=n.interopDefault(o),a=e("dayjs/plugin/customParseFormat"),l=n.interopDefault(a),s=e("./utils/date-format");(0,i.default).extend(l.default);let u=["personal","education","workExperience","equalEmployment"],c=e=>{if(!e?.trim())return null;let t=(0,i.default)(e,s.AUTOFILL_INFO_DATE_FORMAT,!0);return t.isValid()?12*t.year()+t.month():null},d=e=>{let t=e?(0,i.default)(e):(0,i.default)(),r=t.isValid()?t:(0,i.default)();return 12*r.year()+r.month()},f=(e,t={})=>{let r=new Set,{personal:n,education:o,workExperience:i,equalEmployment:a}=e,l=d(t.today),s=["firstName","lastName","email","phone"];for(let e of s)n[e]?.trim()||r.add(`personal.${e}`);for(let e=0;e<o.length;e++){let t=o[e];t.schoolName?.trim()||r.add(`education.${e}.schoolName`),t.accreditation?.trim()||r.add(`education.${e}.accreditation`);let n=c(t.startDate),i=c(t.endDate);t.isCurrent&&null!==n&&n>l&&r.add(`education.${e}.startDate`),t.isCurrent&&null!==i&&i<l&&r.add(`education.${e}.endDate`),null!==n&&null!==i&&i<n&&r.add(`education.${e}.endDate`)}for(let e=0;e<i.length;e++)i[e].companyName?.trim()||r.add(`workExperience.${e}.companyName`),i[e].jobTitle?.trim()||r.add(`workExperience.${e}.jobTitle`);let u=["workAuthorization","sponsorshipStatus","disability","veteran","gender","lgbt","hispanic","ethnicity"];for(let e of u)a[e]?.trim()||r.add(`equalEmployment.${e}`);return a.sexual?.length||r.add("equalEmployment.sexual"),r},p=e=>{for(let t of u)if([...e].some(e=>e.startsWith(t)))return t;return null},m=e=>{for(let t of u)for(let r of e)if(r.startsWith(`${t}.`))return r;return null}
