// @ts-nocheck
/**
 * Breezy ATS — polyglot label phrases and XPath helpers.
 */

export const BREEZY_POLYGLOT_PHRASES = {
  "Full Name": [
    "Volle naam",
    "Nombre completo",
    "Koko nimi",
    "Prénom et nom",
    "Vollständiger Name",
    "氏名",
    "성명",
    "Volledige naam",
    "Imię i nazwisko",
    "Nome completo",
    "Полное имя",
    "Fullständigt namn",
    "Adı ve Soyadı",
    "Повне ім’я",
    "全名",
  ],
  "Email Address": [
    "E-posadres",
    "Dirección de correo electrónico",
    "Sähköpostiosoite",
    "Adresse e-mail",
    "Adresse électronique",
    "E-Mail-Adresse",
    "Eメールアドレス",
    "이메일 주소",
    "E-mailadres",
    "Adres e-mail",
    "Endereço de e-mail",
    "Адрес электронной почты",
    "Indirizzo e-mail",
    "E-postadress",
    "E-posta Adresi",
    "Адреса електронної пошти",
    "电子邮件地址",
  ],
  "Phone Number": [
    "Telefoonnommer",
    "Número de teléfono",
    "Puhelinnumero",
    "N° de téléphone",
    "Telefonnummer",
    "電話番号",
    "전화 번호",
    "Telefoonnummer",
    "Numer telefonu",
    "Número de telefone",
    "Telefone",
    "Номер телефона",
    "Numero di telefono",
    "Telefon Numarası",
    "Номер телефону",
    "电话号码",
  ],
  "Experience Summary": [
    "Opsomming van ondervinding",
    "Experiencia Resumen",
    "Yhteenveto kokemuksesta",
    "Résumé de l’expérience",
    "Zusammenfassung der Erfahrungen",
    "経験の要約",
    "경험 요약",
    "Samenvatting ervaring",
    "Podsumowanie doświadczenia",
    "Resumo de experiência",
    "Краткий обзор опыта работы",
    "Sommario delle Esperienze",
    "Sammanfattning av arbetslivserfarenheten",
    "Deneyim Özeti",
    "Короткий опис трудового досвіду",
    "经验摘要",
  ],
  Education: [
    "Opleiding",
    "Educación",
    "Koulutus",
    "Études",
    "Ausbildung",
    "学歴",
    "교육",
    "Wykształcenie",
    "Formação",
    "Educação",
    "Образование",
    "Studi e formazione",
    "Utbildning",
    "Eğitim",
    "Освіта",
    "教育背景",
  ],
  "Work History": [
    "Werksgeskiedenis",
    "Historial de trabajo",
    "Työhistoria",
    "Antécédents professionnels",
    "Berufslaufbahn",
    "職歴",
    "경력",
    "Loopbaan",
    "Historia zatrudnienia",
    "Experiência profissional",
    "Histórico profissional",
    "Опыт работы",
    "Carriera lavorativa",
    "Jobbhistorik",
    "İş Geçmişi",
    "Професійна біографія",
    "工作经历",
  ],
  "Cover Letter": [
    "Dekbrief",
    "carta de presentación",
    "Saatekirje",
    "Lettre de motivation",
    "Lettre d’accompagnement",
    "Anschreiben",
    "カバーレター",
    "커버레터",
    "Sollicitatiebrief",
    "List motywacyjny",
    "Carta de acompanhamento",
    "Carta de apresentação",
    "Сопроводительное письмо",
    "Lettera di accompagnamento",
    "Personligt brev",
    "Ön Yazı",
    "Мотиваційний лист",
    "求职信",
  ],
  Resume: [
    "Curriculum Vitae",
    "Currículum",
    "Ansioluettelo",
    "Curriculum Vitæ",
    "Lebenslauf",
    "履歴書",
    "이력서",
    "CV",
    "Życiorys",
    "Currículo",
    "Резюме",
    "Curriculum",
    "Öz Geçmiş",
    "резюме",
    "简历",
  ],
  "Desired Salary": [
    "Verwagte salaris",
    "Salario deseado",
    "Toivottu palkka",
    "Salaire souhaité",
    "Gehaltsvorstelungen",
    "希望给与",
    "희망 급여",
    "Gewenst salaris",
    "Oczekiwane wynagrodzenie",
    "Pretensão salarial",
    "Желаемая зарплата",
    "Stipendio desiderato",
    "Önskad lön",
    "İstenen maaş",
    "Бажана зарплата",
    "期望薪资",
  ],
  "Add Education": [
    "Voeg opleiding by",
    "Añadir Educación",
    "Lisää koulutus",
    "Ajouter un cursus d’études",
    "Ausbildung hinzufügen",
    "学歴を追加",
    "교육 추가",
    "Opleiding toevoegen",
    "Dodaj wykształcenie",
    "Adicionar formação",
    "Adicionar Educação",
    "Добавить образование",
    "Aggiungi Studi e formazione",
    "Lägg till utbildning",
    "Eğitim Ekle",
    "Додати освіту",
    "添加教育背景",
  ],
  "Add Position": [
    "Voeg posisie by",
    "Añadir Posición",
    "Lisää työpaikka",
    "Ajouter un poste",
    "Position hinzufügen",
    "求人を追加",
    "직책 추가",
    "Functie toevoegen",
    "Dodaj stanowisko",
    "Adicionar cargo",
    "Добавить вакансию",
    "Aggiungi posizione",
    "Lägg till jobb",
    "Pozisyon Ekle",
    "Додати посаду",
    "添加职位",
  ],
  "Submit Application": [
    "Dien aansoek in",
    "Enviar solicitud",
    "Lähetä hakemus",
    "Soumettre la candidature",
    "Bewerbung übermitteln",
    "応募書類を提出",
    "지원서 제출",
    "Sollicitatie verzenden",
    "Przekaż aplikację",
    "Submeter candidatura",
    "Enviar candidatura",
    "Отправить заявление кандидата",
    "Invia candidatura",
    "Skicka in ansökan",
    "Başvuruyu Gönder",
    "Надіслати заявку кандидата",
    "提交申请",
  ],
}

const normalizePhrase = (text) =>
  text.replace(/\s+/g, " ").trim().toLowerCase()

const phraseToCanonical = /* @__PURE__ */ new Map()
for (let [canonical, translations] of Object.entries(BREEZY_POLYGLOT_PHRASES)) {
  phraseToCanonical.set(normalizePhrase(canonical), canonical)
  for (let translation of translations) {
    phraseToCanonical.set(normalizePhrase(translation), canonical)
  }
}

export function canonicalizeBreezyLabel(label) {
  return phraseToCanonical.get(normalizePhrase(label)) ?? label
}

export function matchesBreezyLabel(label, expected) {
  return (
    canonicalizeBreezyLabel(label) === expected ||
    normalizePhrase(label) === normalizePhrase(expected)
  )
}

export function buildBreezyPolyglotXpathTextCondition(canonicalKey, mapPhrase) {
  let phrases = [
    canonicalKey,
    ...(BREEZY_POLYGLOT_PHRASES[canonicalKey] ?? []),
  ]
  return phrases.map(mapPhrase).join(" or ")
}
