/**
 * Parcel module id: g2QpR
 * Resolved path: nanoid.js
 * Dependencies:
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 *
 * npm-backed (nanoid). Generated by scripts/replace-remaining-vendors-with-npm.mjs — do not hand-edit.
 */

var helpers = e("@parcel/transformer-js/src/esmodule-helpers.js")
helpers.defineInteropFlag(r)

var __jrReq = e

var __mod = (function () {
  var __cjsModule = { exports: {} }
  var module = __cjsModule
  var exports = __cjsModule.exports
;var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// scripts/_remaining-vendor-tmp/entry-g2QpR.mjs
var entry_g2QpR_exports = {};
__export(entry_g2QpR_exports, {
  customAlphabet: () => customAlphabet,
  customRandom: () => customRandom,
  default: () => entry_g2QpR_default,
  nanoid: () => nanoid,
  random: () => random,
  urlAlphabet: () => urlAlphabet
});
module.exports = __toCommonJS(entry_g2QpR_exports);

// node_modules/nanoid/index.browser.js
var index_browser_exports = {};
__export(index_browser_exports, {
  customAlphabet: () => customAlphabet,
  customRandom: () => customRandom,
  nanoid: () => nanoid,
  random: () => random,
  urlAlphabet: () => urlAlphabet
});

// node_modules/nanoid/url-alphabet/index.js
var urlAlphabet = "useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict";

// node_modules/nanoid/index.browser.js
var random = (bytes) => crypto.getRandomValues(new Uint8Array(bytes));
var customRandom = (alphabet, defaultSize, getRandom) => {
  let safeByteCutoff = 256 - 256 % alphabet.length;
  if (safeByteCutoff === 256) {
    let mask = alphabet.length - 1;
    return (size = defaultSize) => {
      if (!size) return "";
      let id = "";
      while (true) {
        let bytes = getRandom(size);
        let j = size;
        while (j--) {
          id += alphabet[bytes[j] & mask];
          if (id.length >= size) return id;
        }
      }
    };
  }
  let step = Math.ceil(1.6 * 256 * defaultSize / safeByteCutoff);
  return (size = defaultSize) => {
    if (!size) return "";
    let id = "";
    while (true) {
      let bytes = getRandom(step);
      let j = step;
      while (j--) {
        if (bytes[j] < safeByteCutoff) {
          id += alphabet[bytes[j] % alphabet.length];
          if (id.length >= size) return id;
        }
      }
    }
  };
};
var customAlphabet = (alphabet, size = 21) => customRandom(alphabet, size | 0, random);
var nanoid = (size = 21) => {
  let id = "";
  let bytes = crypto.getRandomValues(new Uint8Array(size |= 0));
  while (size--) {
    id += urlAlphabet[bytes[size] & 63];
  }
  return id;
};

// scripts/_remaining-vendor-tmp/entry-g2QpR.mjs
var entry_g2QpR_default = void 0 !== void 0 ? void 0 : index_browser_exports;

  var out = module.exports
  if (out && typeof out === "object" && out.__esModule && "default" in out) {
    var names = Object.keys(out).filter(function (k) {
      return k !== "default" && k !== "__esModule"
    })
    if (names.length) return out
    return out.default
  }
  return out
})()

if (typeof __mod === "function") {
  helpers.export(r, "default", function () { return __mod })
  r.default = __mod
} else if (__mod && typeof __mod === "object") {
  for (var __k in __mod) {
    if (Object.prototype.hasOwnProperty.call(__mod, __k) && __k !== "__esModule") {
      ;(function (key) {
        helpers.export(r, key, function () { return __mod[key] })
        r[key] = __mod[key]
      })(__k)
    }
  }
  r.default = __mod.default !== undefined ? __mod.default : __mod
  if (__mod.default !== undefined) {
    helpers.export(r, "default", function () { return __mod.default })
  }
} else {
  r.default = __mod
  helpers.export(r, "default", function () { return __mod })
}
