/**
 * Parcel module id: e8SYa
 * Resolved path: pify.js
 * Dependencies:
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 *
 * npm-backed (pify). Generated by scripts/replace-remaining-vendors-with-npm.mjs — do not hand-edit.
 */

var helpers = e("@parcel/transformer-js/src/esmodule-helpers.js")
helpers.defineInteropFlag(r)

var __jrReq = e

var __mod = (function () {
  var __cjsModule = { exports: {} }
  var module = __cjsModule
  var exports = __cjsModule.exports
;var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// scripts/_remaining-vendor-tmp/entry-e8SYa.mjs
var entry_e8SYa_exports = {};
__export(entry_e8SYa_exports, {
  default: () => entry_e8SYa_default
});
module.exports = __toCommonJS(entry_e8SYa_exports);

// node_modules/pify/index.js
var pify_exports = {};
__export(pify_exports, {
  default: () => pify
});
var processFunction = (function_, options, proxy, unwrapped) => function(...arguments_) {
  const P = options.promiseModule;
  return new P((resolve, reject) => {
    if (options.multiArgs) {
      arguments_.push((...result) => {
        if (options.errorFirst) {
          if (result[0]) {
            reject(result);
          } else {
            result.shift();
            resolve(result);
          }
        } else {
          resolve(result);
        }
      });
    } else if (options.errorFirst) {
      arguments_.push((error, result) => {
        if (error) {
          reject(error);
        } else {
          resolve(result);
        }
      });
    } else {
      arguments_.push(resolve);
    }
    const self = this === proxy ? unwrapped : this;
    Reflect.apply(function_, self, arguments_);
  });
};
var filterCache = /* @__PURE__ */ new WeakMap();
function pify(input, options) {
  options = {
    exclude: [/.+(?:Sync|Stream)$/],
    errorFirst: true,
    promiseModule: Promise,
    ...options
  };
  const objectType = typeof input;
  if (!(input !== null && (objectType === "object" || objectType === "function"))) {
    throw new TypeError(`Expected \`input\` to be a \`Function\` or \`Object\`, got \`${input === null ? "null" : objectType}\``);
  }
  const filter = (target, key) => {
    let cached = filterCache.get(target);
    if (!cached) {
      cached = {};
      filterCache.set(target, cached);
    }
    if (key in cached) {
      return cached[key];
    }
    const match = (pattern) => typeof pattern === "string" || typeof key === "symbol" ? key === pattern : pattern.test(key);
    const descriptor = Reflect.getOwnPropertyDescriptor(target, key);
    const writableOrConfigurableOwn = descriptor === void 0 || descriptor.writable || descriptor.configurable;
    const included = options.include ? options.include.some((element) => match(element)) : !options.exclude.some((element) => match(element));
    const shouldFilter = included && writableOrConfigurableOwn;
    cached[key] = shouldFilter;
    return shouldFilter;
  };
  const cache = /* @__PURE__ */ new WeakMap();
  const proxy = new Proxy(input, {
    apply(target, thisArg, args) {
      const cached = cache.get(target);
      if (cached) {
        return Reflect.apply(cached, thisArg, args);
      }
      const pified = options.excludeMain ? target : processFunction(target, options, proxy, target);
      cache.set(target, pified);
      return Reflect.apply(pified, thisArg, args);
    },
    get(target, key) {
      const property = target[key];
      if (!filter(target, key) || property === Function.prototype[key]) {
        return property;
      }
      const cached = cache.get(property);
      if (cached) {
        return cached;
      }
      if (typeof property === "function") {
        const pified = processFunction(property, options, proxy, target);
        cache.set(property, pified);
        return pified;
      }
      return property;
    }
  });
  return proxy;
}

// scripts/_remaining-vendor-tmp/entry-e8SYa.mjs
var entry_e8SYa_default = pify !== void 0 ? pify : pify_exports;

  var out = module.exports
  if (out && typeof out === "object" && out.__esModule && "default" in out) {
    var names = Object.keys(out).filter(function (k) {
      return k !== "default" && k !== "__esModule"
    })
    if (names.length) return out
    return out.default
  }
  return out
})()

if (typeof __mod === "function") {
  helpers.export(r, "default", function () { return __mod })
  r.default = __mod
} else if (__mod && typeof __mod === "object") {
  for (var __k in __mod) {
    if (Object.prototype.hasOwnProperty.call(__mod, __k) && __k !== "__esModule") {
      ;(function (key) {
        helpers.export(r, key, function () { return __mod[key] })
        r[key] = __mod[key]
      })(__k)
    }
  }
  r.default = __mod.default !== undefined ? __mod.default : __mod
  if (__mod.default !== undefined) {
    helpers.export(r, "default", function () { return __mod.default })
  }
} else {
  r.default = __mod
  helpers.export(r, "default", function () { return __mod })
}
