/**
 * Parcel module id: ffRFv
 * Resolved path: zustand.js
 * Dependencies:
 *   zustand-vanilla -> ei7yf  =>  zustand-vanilla.js
 *   zustand-react -> 7OAlZ  =>  zustand-react.js
 *
 * npm-backed (zustand). Generated by scripts/replace-small-vendors-with-npm.mjs — do not hand-edit.
 */

var vanillaStoreApi = e("zustand-vanilla")
var reactStoreApi = e("zustand-react")

function reexportNamedExports(sourceModule) {
  Object.keys(sourceModule).forEach(function (exportName) {
    if (exportName === "default") return
    if (Object.prototype.hasOwnProperty.call(r, exportName)) return
    Object.defineProperty(r, exportName, {
      enumerable: true,
      get: function () {
        return sourceModule[exportName]
      }
    })
  })
}

reexportNamedExports(vanillaStoreApi)
reexportNamedExports(reactStoreApi)
