/**
 * Parcel module id: 8QXHm
 * Resolved path: @plasmohq/storage/hook.js
 * Dependencies:
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 *   react -> 329PG  =>  react-reexport.js
 *   pify -> e8SYa  =>  pify.js
 *   @plasmohq/storage -> 9RCRe  =>  @plasmohq/storage.js
 *
 * npm-backed (@plasmohq/storage/hook). Generated by scripts/replace-remaining-vendors-with-npm.mjs — do not hand-edit.
 */

var helpers = e("@parcel/transformer-js/src/esmodule-helpers.js")
helpers.defineInteropFlag(r)

var __jrReq = e

var __mod = (function () {
  var __cjsModule = { exports: {} }
  var module = __cjsModule
  var exports = __cjsModule.exports
;var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __reExport = (target, mod, secondTarget) => (__copyProps(target, mod, "default"), secondTarget && __copyProps(secondTarget, mod, "default"));
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// scripts/_remaining-vendor-tmp/entry-8QXHm.mjs
var entry_8QXHm_exports = {};
__export(entry_8QXHm_exports, {
  default: () => entry_8QXHm_default
});
module.exports = __toCommonJS(entry_8QXHm_exports);
__reExport(entry_8QXHm_exports, require("@plasmohq/storage/hook"), module.exports);
var __ns = __toESM(require("@plasmohq/storage/hook"), 1);
var entry_8QXHm_default = __ns.default !== void 0 ? __ns.default : __ns;

  var out = module.exports
  if (out && typeof out === "object" && out.__esModule && "default" in out) {
    var names = Object.keys(out).filter(function (k) {
      return k !== "default" && k !== "__esModule"
    })
    if (names.length) return out
    return out.default
  }
  return out
})()

if (typeof __mod === "function") {
  helpers.export(r, "default", function () { return __mod })
  r.default = __mod
} else if (__mod && typeof __mod === "object") {
  for (var __k in __mod) {
    if (Object.prototype.hasOwnProperty.call(__mod, __k) && __k !== "__esModule") {
      ;(function (key) {
        helpers.export(r, key, function () { return __mod[key] })
        r[key] = __mod[key]
      })(__k)
    }
  }
  r.default = __mod.default !== undefined ? __mod.default : __mod
  if (__mod.default !== undefined) {
    helpers.export(r, "default", function () { return __mod.default })
  }
} else {
  r.default = __mod
  helpers.export(r, "default", function () { return __mod })
}
