/**
 * Parcel module id: k4CP3
 * Resolved path: src/contents/sites/pinpointhq/country.js
 * Dependencies:
 *   @parcel/transformer-js/src/esmodule-helpers.js -> cHUbl  =>  @parcel/transformer-js/src/esmodule-helpers.js
 *   ~utils/delay -> am614  =>  src/utils/delay.js
 */

var n=e("@parcel/transformer-js/src/esmodule-helpers.js");n.defineInteropFlag(r),n.export(r,"PINPOINT_COUNTRY_VISIBLE_VALUE_SELECTOR",()=>a),n.export(r,"PINPOINT_COUNTRY_NATIVE_SELECT",()=>s),n.export(r,"hasPinpointAddressCountryControl",()=>u),n.export(r,"isPinpointCountryCommitSettled",()=>d),n.export(r,"isPinpointCountrySelectionSettled",()=>f),n.export(r,"getPinpointAddressSchemaSignature",()=>p),n.export(r,"isPinpointAddressSchemaCompatibleWithCountry",()=>m),n.export(r,"waitForPinpointAddressSchemaSettlement",()=>h),n.export(r,"isMainPinpointCountryRule",()=>g),n.export(r,"runPinpointCountryPrefill",()=>b);var o=e("~utils/delay");let i="application_form[application][country]",a=".react-select__single-value",l='[id^="Shared::Form::Address-react-component-"]',s="select#application_form\\[application\\]\\[country\\]";function u(e=document){let t=e.querySelector(s);return!!t?.closest("#address-country")}function c(e){return String(e??"").replace(/\s+/g," ").trim().toLowerCase()}function d({expectedCode:e,expectedLabel:t,nativeCode:r,submittedCode:n,visibleLabel:o}){return f({expectedCode:e,expectedLabel:t,nativeCode:r,submittedCode:n,visibleLabel:o})&&c(n)===c(e)}function f({expectedCode:e,expectedLabel:t,nativeCode:r,visibleLabel:n}){return c(r)===c(e)&&c(n)===c(t)}function p(e=document){let t=e.querySelector(l);return t?Array.from(t.querySelectorAll(".external-form__label")).map(e=>c(e.textContent)).filter(Boolean).join("|"):""}function m(e,t){let r=new Set(String(e??"").split("|").map(c).filter(Boolean)),n=String(t??"").trim().toUpperCase();if("GB"===n)return r.has("postcode");if("US"===n){let e=["state","state / province","state/province"].some(e=>r.has(e)),t=["zipcode","zip code","zip"].some(e=>r.has(e));return e&&t}return!1}async function h(e,t,r={}){let n=r.maxAttempts??300,i=r.pollMs??50,a=r.stableReads??2,l="",s=0;for(let r=0;r<n;r++){(r>0||i>0)&&await (0,o.delay)(i);let n=e();if(!n){l="",s=0;continue}if(n===l?s+=1:(l=n,s=1),n!==t&&s>=a)return!0}return!!t&&l===t&&s>=a}function g(e){let t=e.$input;return!!(t&&"SELECT"===t.tagName&&(t.name===i||t.id===i)&&t.closest("#address-country"))}async function b(e){try{let t=await e.fetchAutofillInfo(),r=String(t?.location?.country??"").trim();if(console.info(`[PinpointHQ][Country] autofill-info-read countryProvided=${!!r}`),!r)return{country:null,countryCode:"",committed:!1};let n=await e.fillCountry(r);return{country:r,countryCode:n.countryCode,committed:n.committed}}catch(r){let e=r instanceof Error?r.name:"unknown",t=r instanceof ReferenceError?r.message:e;return console.info(`[PinpointHQ][Country] autofill-info-read-failed error=${e} detail=${t}`),{country:null,countryCode:"",committed:!1}}}
